# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  SIM_config = release

else ifeq ($(config),debug)
  SIM_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := SIM

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SIM:
ifneq (,$(SIM_config))
	@echo "==== Building SIM ($(SIM_config)) ===="
	@${MAKE} --no-print-directory -C . -f SIM.make config=$(SIM_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f SIM.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SIM"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"